package main

import (
	AwsUtils "../../internal"
	DataService "../../internal"
	ModelUtils "../../internal"
	Model "../../model"
	Tables "../../model/tables"
	"context"
	"fmt"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
	"github.com/aws/aws-sdk-go/service/dynamodb/expression"
	"log"
)

var (
	db = AwsUtils.GetDynamoDbClient("eu-central-1")
)

//TODO: change update with
// itemInput := &dynamodb.UpdateItemInput{
//		TableName: aws.String(tableName),
//	}
func Handler(ctx context.Context, event AwsUtils.RequestEvent) (AwsUtils.Response, error) {
	log.Println("begin !!")
	//log.Println(event.Context)
	//lc, _ := lambdacontext.FromContext(ctx)
	//log.Print(lc.Identity.CognitoIdentityPoolID)
	//db := Utils.GetDynamoDbClient()
	log.Println(event.Body)
	log.Println(event.Params)
	log.Println(event.Context)

	httpMethod := event.Context["http-method"]
	switch httpMethod {
	case "GET":
		return AwsUtils.Response{StatusCode: 200, Body: listActiveGames()}, nil
	case "PUT", "POST":
		email := AwsUtils.GetUsernameFromJwtToken(event.Params["header"]["Authorization"])
		gameMap := event.Body
		if gameMap["id"] == nil {
			return AwsUtils.Response{StatusCode: 200, Body: addGame(event.Body, email)}, nil
		} else {
			return AwsUtils.Response{StatusCode: 200, Body: updateGame(event.Body, email)}, nil
		}
	case "DELETE":
		//TODO: authorization is needed, adminGames pages can be different...
		return AwsUtils.Response{StatusCode: 200, Body: deleteGame(event.Body)}, nil
		//return deleteGame(event.Params["id"])
	default:
		return AwsUtils.Response{StatusCode: 405, ErrorMessage: "unsupported operation: " + httpMethod}, nil
	}
}

func listActiveGames() []Model.Game {
	//ex: https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/expression/examples_test.go
	filt := expression.Name("status").Equal(expression.Value("active"))
	expr, err := expression.NewBuilder().WithFilter(filt).Build()
	if err != nil {
		fmt.Println(err)
	}
	games, err := AwsUtils.ListGames(Tables.GAMES, expr)
	if err != nil {
		log.Println("Error occurred.")
		log.Println(err)
	}
	return games
}

func deleteGame(gameMap map[string]interface{}) []Model.Game {
	log.Println("delete game...")
	gameMap["status"] = "deleted"
	games, err := saveGame(gameMap)
	if err != nil {
		log.Println("Error occurred.")
		log.Println(err)
	}
	return games
}

func deleteGameById(id string) ([]Model.Game, error) {
	log.Println("deleteGame...")

	key, err := dynamodbattribute.MarshalMap(id)
	if err != nil {
		fmt.Println(err.Error())
		return nil, err
	}

	input := &dynamodb.GetItemInput{
		Key:       key,
		TableName: aws.String(Tables.GAMES),
	}

	result, err := db.GetItem(input)
	if err != nil {
		fmt.Println(err.Error())
		return nil, err
	}

	var game Model.Game
	err = dynamodbattribute.UnmarshalMap(result.Item, &game)
	if err != nil {
		fmt.Println(err.Error())
		return nil, err
	}

	game.Status = "deleted"
	//return saveGame(game)
	return nil, nil
}

func addGame(gameMap map[string]interface{}, email string) []Model.Game {
	var game Model.Game
	// generated by default
	game.Id = ModelUtils.GenerateKey(10)
	game.RoomPassword = ModelUtils.GenerateKey(8)
	game.Status = "active"
	game.RegisteredUserCount = 0
	currentTimeMillis := AwsUtils.CurrentTimeMillis()
	game.InsertedAt = currentTimeMillis
	game.InsertedBy = email
	game.UpdatedAt = currentTimeMillis
	game.UpdatedBy = email
	// added from request
	game.GameDate = gameMap["gameDate"].(string)
	game.League = gameMap["league"].(string)
	game.Type = gameMap["type"].(string)
	game.Map = gameMap["map"].(string)
	game.Price = gameMap["price"].(float64)

	var games []Model.Game

	err := DataService.SaveGame(game)
	if err != nil {
		log.Println("Error occurred.")
		log.Println(err)
		//return nil, err
	} else {
		games = append(games, game)
	}

	return games
}

func updateGame(gameMap map[string]interface{}, email string) []Model.Game {
	log.Println("updateGame...")
	currentTimeMillis := AwsUtils.CurrentTimeMillis()
	gameMap["updatedAt"] = currentTimeMillis
	gameMap["updatedBy"] = email
	games, err := saveGame(gameMap)
	if err != nil {
		log.Println("Error occurred.")
		log.Println(err)
	}
	return games
}

func saveGame(gameMap map[string]interface{}) ([]Model.Game, error) {
	log.Println("game will be saved...")
	log.Println(gameMap)
	av, err := dynamodbattribute.MarshalMap(gameMap)

	if err != nil {
		fmt.Println("Got error marshalling map:")
		fmt.Println(err.Error())
		return nil, err
	}

	input := &dynamodb.PutItemInput{
		Item:      av,
		TableName: aws.String(Tables.GAMES),
	}

	// todo put item unique
	_, err = db.PutItem(input)

	if err != nil {
		fmt.Println("Got error calling PutItem:")
		fmt.Println(err.Error())
		return nil, err
	}
	var games []Model.Game
	var game Model.Game
	err = dynamodbattribute.UnmarshalMap(av, &game)
	if err != nil {
		return nil, err
	}
	games = append(games, game)
	return games, nil
}

func main() {
	//listActiveGames()
	lambda.Start(Handler)
}
