package main

import (
	AwsUtils "../../internal"
	DataService "../../internal"
	ModelUtils "../../internal"
	Model "../../model"
	Tables "../../model/tables"
	"context"
	"fmt"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
	"github.com/aws/aws-sdk-go/service/dynamodb/expression"
	"log"
)

var (
	db = AwsUtils.GetDynamoDbClient("eu-central-1")
)

func Handler(ctx context.Context, event AwsUtils.RequestEvent) (AwsUtils.Response, error) {
	log.Println("begin !!")
	operator := AwsUtils.GetUsernameFromJwtTokenForAdmin(event.Params["header"]["Authorization"])
	httpMethod := event.Context["http-method"]
	switch httpMethod {
	case "GET":
		status := event.Params["querystring"]["status"]
		if status != "" {
			return AwsUtils.Response{StatusCode: 200, Body: listGamesWithStatus(status)}, nil
		} else {
			return AwsUtils.Response{StatusCode: 200, Body: listGames()}, nil
		}
	case "PUT", "POST":
		gameMap := event.Body
		if gameMap["id"] == nil {
			return AwsUtils.Response{StatusCode: 200, Body: addGame(event.Body, operator)}, nil
		} else {
			return AwsUtils.Response{StatusCode: 200, Body: updateGame(event.Body, operator)}, nil
		}
	case "DELETE":
		return deleteGame(event.Body, operator)
	default:
		return AwsUtils.Response{StatusCode: 405, ErrorMessage: "unsupported operation: " + httpMethod}, nil
	}
}

func listGames() []Model.Game {
	//ex: https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/expression/examples_test.go
	expr, err := expression.NewBuilder().Build()
	if err != nil {
		fmt.Println(err)
	}
	games, err := AwsUtils.ListGamesWithPassword(Tables.GAMES, expr)
	if err != nil {
		log.Println("Error occurred.")
		log.Println(err)
	}
	return games
}

func listGamesWithStatus(status string) []Model.Game {
	filt := expression.Name("status").Equal(expression.Value(status))
	expr, err := expression.NewBuilder().WithFilter(filt).Build()
	if err != nil {
		fmt.Println(err)
	}
	games, err := AwsUtils.ListGamesWithPassword(Tables.GAMES, expr)
	if err != nil {
		log.Println("Error occurred.")
		log.Println(err)
	}
	return games
}

func deleteGame(gameMap map[string]interface{}, operator string) (AwsUtils.Response, error) {
	log.Println("delete game...")
	gameMap["status"] = "deleted"
	gameMap["updatedBy"] = operator
	games, err := saveGame(gameMap)
	if err != nil {
		return AwsUtils.Response{StatusCode: 400, ErrorMessage: err.Error()}, err
	}
	return AwsUtils.Response{StatusCode: 200, Body: games}, nil
}

func deleteGameById(id string) ([]Model.Game, error) {
	log.Println("deleteGame...")

	key, err := dynamodbattribute.MarshalMap(id)
	if err != nil {
		fmt.Println(err.Error())
		return nil, err
	}

	input := &dynamodb.GetItemInput{
		Key:       key,
		TableName: aws.String(Tables.GAMES),
	}

	result, err := db.GetItem(input)
	if err != nil {
		fmt.Println(err.Error())
		return nil, err
	}

	var game Model.Game
	err = dynamodbattribute.UnmarshalMap(result.Item, &game)
	if err != nil {
		fmt.Println(err.Error())
		return nil, err
	}

	game.Status = "deleted"
	//return saveGame(game)
	return nil, nil
}

func addGame(gameMap map[string]interface{}, operator string) []Model.Game {
	fmt.Println(gameMap)
	// generated by default
	gameMap["id"] = ModelUtils.GenerateKey(10)
	gameMap["roomPassword"] = ModelUtils.GenerateKey(8)
	gameMap["status"] = "active"
	gameMap["registeredUserCount"] = 0
	currentTimeMillis := AwsUtils.CurrentTimeMillis()
	gameMap["insertedAt"] = currentTimeMillis
	gameMap["insertedBy"] = operator
	gameMap["updatedAt"] = currentTimeMillis
	gameMap["updatedBy"] = operator
	return updateGame(gameMap, operator)
}

func updateGame(gameMap map[string]interface{}, operator string) []Model.Game {
	log.Println("updateGame...")
	currentTimeMillis := AwsUtils.CurrentTimeMillis()
	gameMap["updatedAt"] = currentTimeMillis
	gameMap["updatedBy"] = operator
	games, err := saveGame(gameMap)
	if err != nil {
		log.Println("Error occurred.")
		log.Println(err)
	}
	return games
}

func saveGame(gameMap map[string]interface{}) ([]Model.Game, error) {
	log.Println("game will be saved...")
	log.Println(gameMap)
	gameId := gameMap["id"].(string)
	status := gameMap["status"].(string)
	if status == "cancelled" || status == "deleted" {
		//fmt.Println(">>> gameId: " + gameId)
		game := AwsUtils.GetGameById(gameId)
		gameUsers := AwsUtils.GetGameUsersByGameId(gameId)
		for _, userId := range gameUsers.Users {
			//fmt.Println(">>> userId: " + userId)
			user := AwsUtils.GetUserById(userId)
			// TODO : should all process in a TX
			err := DataService.UnregisterUserToGame(user, game)
			if err != nil {
				fmt.Println("User can't be unregistered: " + user.Username)
				return nil, err
			}
		}
	}

	av, err := dynamodbattribute.MarshalMap(gameMap)
	if err != nil {
		fmt.Println("Got error marshalling map:")
		fmt.Println(err.Error())
		return nil, err
	}

	input := &dynamodb.PutItemInput{
		Item:      av,
		TableName: aws.String(Tables.GAMES),
	}

	// todo put item unique
	_, err = db.PutItem(input)
	if err != nil {
		fmt.Println("Got error calling PutItem:")
		fmt.Println(err.Error())
		return nil, err
	}

	var games []Model.Game
	var game Model.Game
	err = dynamodbattribute.UnmarshalMap(av, &game)
	if err != nil {
		return nil, err
	}
	games = append(games, game)
	return games, nil
}

func main() {
	lambda.Start(Handler)
}
