package main

import (
	AwsUtils "../../internal"
	DataService "../../internal"
	ModelUtils "../../internal"
	Model "../../model"
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"log"
)

func Handler(event events.CognitoEventUserPoolsPostConfirmation) (events.CognitoEventUserPoolsPostConfirmation, error) {
	log.Println("")
	log.Printf("%v\n", event.Request.UserAttributes)
	log.Printf("PostConfirmation for userRegistered: %s with email: %s\n", event.UserName, event.Request.UserAttributes["email"])
	var user Model.User
	// generated by default
	user.Id = ModelUtils.GenerateKey(10)
	user.Status = "active"
	user.Balance = 0
	currentTimeMillis := AwsUtils.CurrentTimeMillis()
	user.InsertedAt = currentTimeMillis
	user.InsertedBy = "system"
	user.UpdatedAt = currentTimeMillis
	user.UpdatedBy = "system"
	// added from request
	user.Username = event.Request.UserAttributes["name"]
	user.Email = event.Request.UserAttributes["email"]
	user.SecretQuestion = event.Request.UserAttributes["custom:secretQuestion"]
	user.SecretAnswer = event.Request.UserAttributes["custom:secretAnswer"]

	err := DataService.SaveUser(user)
	return event, err
}

func main() {
	lambda.Start(Handler)
}
